# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e433c4a6e42615182566aab70824ff21586718c49f2d7f05b1489c8f96400c8f3cb8d774bf40b1bb1cf2805b14b88bbb97e29dc02cb47f4aeed8d055db426db9

test:
  secret_key_base: ce7719d85f2543b7e139b7ae54b6a469d2b7aee62e5addd274547c4ee4eeb6dd819153c86df040fbbd9f78431d2f73634254820b71edf3889ea0247fbbbed38b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
